# Generated by Django 5.0.1 on 2024-01-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autodidact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="autodidact/static/autodidact/file/"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="autodidact/static/autodidact/video/"
            ),
        ),
    ]
